# =========================
# Stage 2: Python + Spark NLP
# =========================
FROM spark-runtime

# Upgrade pip
RUN pip3 install --upgrade pip

# Python deps (this is what you'll change often)
RUN pip3 install \
	ipykernel \
	pyspark==3.5.0 \
	spark-nlp \
	pandas \
	scikit-learn \
	tqdm \
	gensim \
	fastapi \
	uvicorn \ 
	pydantic

# Setup port for FastAPI
EXPOSE 8000

# Workspace
WORKDIR /workspace

CMD ["bash"]