# #Download base image ubuntu 18.04
# FROM ubuntu:22.04

# WORKDIR /workspace


# ENV NB_USER=jovyan
# ENV NB_UID=1000
# ENV HOME=/home/${NB_USER}

# ENV PYSPARK_PYTHON=python3
# ENV PYSPARK_DRIVER_PYTHON=python3

# RUN apt-get update && apt-get install -y \
# 	tar \
# 	wget \
# 	bash \
# 	rsync \
# 	gcc \
# 	libfreetype6-dev \
# 	libhdf5-serial-dev \
# 	libpng-dev \
# 	libzmq3-dev \
# 	python3=3.10.6-1~22.04 \
# 	python3-dev \
# 	python3-pip \
# 	unzip \
# 	pkg-config \
# 	software-properties-common \
# 	graphviz

# RUN adduser --disabled-password \
# 	--gecos "Default user" \
# 	--uid ${NB_UID} \
# 	${NB_USER}

# # Install OpenJDK-11
# RUN apt-get update && \
# 	apt-get install -y openjdk-11-jdk && \
# 	apt-get install -y ant && \
# 	apt-get clean;

# # Fix certificate issues
# RUN apt-get update && \
# 	apt-get install ca-certificates-java && \
# 	apt-get clean && \
# 	update-ca-certificates -f;
# # Setup JAVA_HOME -- useful for docker commandline
# ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
# RUN export JAVA_HOME

# # Spark versions compatible with Spark NLP
# ENV SPARK_VERSION=3.5.0
# ENV HADOOP_VERSION=3
# ENV SPARK_HOME=/opt/spark

# RUN wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
# 	tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
# 	mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} && \
# 	rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

# ENV PATH="${SPARK_HOME}/bin:${PATH}"

# RUN echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/" >> ~/.bashrc

# RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# RUN pip3 install --upgrade pip
# # You only need pyspark and spark-nlp paclages to use Spark NLP
# # The rest of the PyPI packages are here as examples
# RUN pip install pyspark spark-nlp pandas scikit-learn matplotlib tqdm nlu nltk gensim


# USER root
# RUN chown -R ${NB_UID} ${HOME}
# USER ${NB_USER}

# WORKDIR ${HOME}

# # Specify the default command to run
# CMD [ "bash" ]

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
# Versions
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH=${SPARK_HOME}/bin:${JAVA_HOME}/bin:${PATH}

RUN apt-get update && apt-get install -y \
	openjdk-11-jdk \
	python3 \
	python3-pip \
	python3-dev \
	wget \
	bash \
	ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

# Install Spark
RUN wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
	tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
	mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} && \
	rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

RUN spark-submit --version