FROM eclipse-temurin:11-jre-jammy

# Versions
ENV DEBIAN_FRONTEND=noninteractive
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH=${SPARK_HOME}/bin:${PATH}

RUN apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	wget \
	ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

# Install Spark
RUN wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
	tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
	mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} && \
	rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
	rm -rf \
	${SPARK_HOME}/examples \
	${SPARK_HOME}/data \
	${SPARK_HOME}/R \
	${SPARK_HOME}/kubernetes/tests

# Sanity check (optional, but nice)
RUN spark-submit --version